<script >
export default{
  components :{}
}

</script>

<template>
  <div class="home">
    <h1>homepage</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat excepturi tenetur eligendi aliquam voluptas sit soluta odio distinctio explicabo enim veritatis, iusto labore, alias voluptatibus cum expedita esse sed optio illo corrupti? Facilis vitae ex mollitia a impedit natus dolorem molestiae necessitatibus, veritatis labore sint. Illo ab, eum voluptate facilis ipsa architecto. Aliquid rerum obcaecati doloremque voluptate dolores. Veritatis veniam, maxime accusamus iste minima nostrum reprehenderit. Qui adipisci libero modi fugiat saepe temporibus praesentium quidem quis laboriosam, iusto voluptates nobis cum perspiciatis ut corporis voluptatem consequatur nisi illum, similique ea? Assumenda, error asperiores mollitia placeat aspernatur neque excepturi tempore necessitatibus? Nisi sunt vel vitae, exercitationem, recusandae atque quaerat deleniti totam magni quidem veniam! Repellendus itaque quae ullam nesciunt. Doloribus assumenda excepturi eius esse corrupti asperiores magni et, error, iure molestias nostrum nemo unde animi, omnis ipsum accusamus ad possimus sapiente quam. Nisi accusamus quas iure illo et fugiat hic. Iste voluptates quisquam eveniet? Consequuntur quos assumenda deleniti qui doloremque soluta cupiditate praesentium illo laboriosam? Aliquam, officiis et. Minus voluptatum totam explicabo quibusdam quia repellendus accusantium fuga, numquam aperiam velit dicta, optio ipsum et esse doloremque perspiciatis maiores deserunt laboriosam adipisci molestiae ipsam exercitationem est! Consequatur labore facere similique soluta repellat est dolor fuga sint facilis quia deleniti sed praesentium dolore cupiditate, sunt cum quas, eligendi odit optio laborum! Deserunt fugiat maxime deleniti animi ratione quas quos fuga, consequatur tenetur eaque quod dolorum. Quasi, quia dignissimos est eaque modi laborum. Perferendis laboriosam voluptatibus obcaecati quidem explicabo iste repudiandae laudantium temporibus molestias minima, voluptas doloremque illum error omnis blanditiis sunt libero natus eaque distinctio cumque facere impedit dignissimos aperiam. Velit facilis ullam, eveniet voluptatibus ipsam libero distinctio doloribus necessitatibus cum illum minus deserunt ea tempora vitae dicta culpa reiciendis debitis ad impedit. Magni iste necessitatibus a vitae pariatur delectus commodi consequatur aliquam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat excepturi tenetur eligendi aliquam voluptas sit soluta odio distinctio explicabo enim veritatis, iusto labore, alias voluptatibus cum expedita esse sed optio illo corrupti? Facilis vitae ex mollitia a impedit natus dolorem molestiae necessitatibus, veritatis labore sint. Illo ab, eum voluptate facilis ipsa architecto. Aliquid rerum obcaecati doloremque voluptate dolores. Veritatis veniam, maxime accusamus iste minima nostrum reprehenderit. Qui adipisci libero modi fugiat saepe temporibus praesentium quidem quis laboriosam, iusto voluptates nobis cum perspiciatis ut corporis voluptatem consequatur nisi illum, similique ea? Assumenda, error asperiores mollitia placeat aspernatur neque excepturi tempore necessitatibus? Nisi sunt vel vitae, exercitationem, recusandae atque quaerat deleniti totam magni quidem veniam! Repellendus itaque quae ullam nesciunt. Doloribus assumenda excepturi eius esse corrupti asperiores magni et, error, iure molestias nostrum nemo unde animi, omnis ipsum accusamus ad possimus sapiente quam. Nisi accusamus quas iure illo et fugiat hic. Iste voluptates quisquam eveniet? Consequuntur quos assumenda deleniti qui doloremque soluta cupiditate praesentium illo laboriosam? Aliquam, officiis et. Minus voluptatum totam explicabo quibusdam quia repellendus accusantium fuga, numquam aperiam velit dicta, optio ipsum et esse doloremque perspiciatis maiores deserunt laboriosam adipisci molestiae ipsam exercitationem est! Consequatur labore facere similique soluta repellat est dolor fuga sint facilis quia deleniti sed praesentium dolore cupiditate, sunt cum quas, eligendi odit optio laborum! Deserunt fugiat maxime deleniti animi ratione quas quos fuga, consequatur tenetur eaque quod dolorum. Quasi, quia dignissimos est eaque modi laborum. Perferendis laboriosam voluptatibus obcaecati quidem explicabo iste repudiandae laudantium temporibus molestias minima, voluptas doloremque illum error omnis blanditiis sunt libero natus eaque distinctio cumque facere impedit dignissimos aperiam. Velit facilis ullam, eveniet voluptatibus ipsam libero distinctio doloribus necessitatibus cum illum minus deserunt ea tempora vitae dicta culpa reiciendis debitis ad impedit. Magni iste necessitatibus a vitae pariatur delectus commodi consequatur aliquam!</p>
  </div>
</template>


<style scoped>

</style>
